# Generated by Django 2.2.4 on 2019-08-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
